module.exports = {
    content: [
        './pages/**/*.{js,ts,jsx,tsx}',
        './components/**/*.{js,ts,jsx,tsx}',
    ],
    theme: {
        extend: {
            colors: {
                maha: {
                    100: '#F9D4EB',
                    200: '#F4ABDE',
                    300: '#DE7BC9',
                    400: '#BE54B0',
                    500: '#93268F',
                    600: '#791B7E',
                    700: '#5D1369',
                    800: '#440C55',
                    900: '#320746',
                },
                'maha-green': {
                    100: '#E6F7CD',
                    200: '#C8F09F',
                    300: '#98D368',
                    400: '#65A73D',
                    500: '#2E6D11',
                    600: '#205D0C',
                    700: '#154E08',
                    800: '#0C3F05',
                    900: '#053403',
                },
                hijau: '#8CC73F',
                kuning: '#FFDE86',
                jingga: '#F5BC76',
                pink: '#FA8E8E',
                merah: '#DE1B1B',
                content: '#FBF9FA',
                table: '#F1F5EB',
                'btn-accordion': '#7DB737',
                'green-light': '#DDEEC6',
                'green-dark': '#2E6D11',
                'green-active': '#2A854E',
                'green-active-inner': '#E1FAEB',
                'green-active-outer': '#7DDBA3',
            },
            fontFamily: {
                sans: ['Poppins', 'sans-serif'],
            },
        },
        listStyleType: {
            none: 'none',
            disc: 'disc',
            decimal: 'decimal',
            square: 'square',
            roman: 'upper-roman',
        },
    },
    plugins: [],
}
